spring:
  #thymelaef配置
  thymeleaf:
    #缓存
    cache: false
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
    username: root
    password: 123456
    hikari:
      # ????
      pool-name: DateHikariCP
      # ???????
      minimum-idle: 5
      # ?????????????600000?10???
      idle-timeout: 180000
      # ????????????10
      maximum-pool-size: 10
      # ?????????????????????,????true
      auto-commit: true
      # ??????????????????0???????????1800000?30??
      max-lifetime: 1800000
      # ????????????30000?30??
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1
  redis:
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        min-idle: 5

  resources:
    #启用默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cache control:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源链中启用缓存，默认启用
      cache: true
      #启用资源链，默认禁用
      enabled: true
    #启用压缩资源(gzip,brotli)解析,默认禁用
      compressed: true
      #启用H5应用缓存，默认禁用
      html-application-cache: true
    #静态资源位置
    static-locations: classpath:/static/

#Mybatis-plus??
mybatis-plus:
  #??Mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #??Mybatis????????(???????)
  type-aliases-package: com.lxw.seckill.pojo

#Mybatis SQL??(???????????Mapper.xml????)
logging:
  level:
    com.liu.seckill.mapper: debug
